// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDatabase() {
  return window['go']['main']['App']['ClearDatabase']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetClientes(arg1, arg2) {
  return window['go']['main']['App']['GetClientes'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetISAMInfo() {
  return window['go']['main']['App']['GetISAMInfo']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetMovimientos(arg1, arg2) {
  return window['go']['main']['App']['GetMovimientos'](arg1, arg2);
}

export function GetProductos(arg1, arg2) {
  return window['go']['main']['App']['GetProductos'](arg1, arg2);
}

export function GetRecordDetail(arg1) {
  return window['go']['main']['App']['GetRecordDetail'](arg1);
}

export function GetSentRecords(arg1, arg2) {
  return window['go']['main']['App']['GetSentRecords'](arg1, arg2);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function IsPaused() {
  return window['go']['main']['App']['IsPaused']();
}

export function IsSyncing() {
  return window['go']['main']['App']['IsSyncing']();
}

export function PauseSync() {
  return window['go']['main']['App']['PauseSync']();
}

export function RefreshCache(arg1) {
  return window['go']['main']['App']['RefreshCache'](arg1);
}

export function ResendRecord(arg1) {
  return window['go']['main']['App']['ResendRecord'](arg1);
}

export function ResumeSync() {
  return window['go']['main']['App']['ResumeSync']();
}

export function SaveConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchSentRecords(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchSentRecords'](arg1, arg2, arg3);
}

export function SearchSentRecordsWithDates(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SearchSentRecordsWithDates'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}
