// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDatabase() {
  return window['go']['main']['App']['ClearDatabase']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetCartera(arg1, arg2) {
  return window['go']['main']['App']['GetCartera'](arg1, arg2);
}

export function GetClientes(arg1, arg2) {
  return window['go']['main']['App']['GetClientes'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetExtfhStatus() {
  return window['go']['main']['App']['GetExtfhStatus']();
}

export function GetISAMInfo() {
  return window['go']['main']['App']['GetISAMInfo']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetMovimientos(arg1, arg2) {
  return window['go']['main']['App']['GetMovimientos'](arg1, arg2);
}

export function GetProductos(arg1, arg2) {
  return window['go']['main']['App']['GetProductos'](arg1, arg2);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetSyncHistory(arg1, arg2) {
  return window['go']['main']['App']['GetSyncHistory'](arg1, arg2);
}

export function IsPaused() {
  return window['go']['main']['App']['IsPaused']();
}

export function IsSyncing() {
  return window['go']['main']['App']['IsSyncing']();
}

export function LookupByNIT(arg1) {
  return window['go']['main']['App']['LookupByNIT'](arg1);
}

export function LookupCarteraPorNIT(arg1) {
  return window['go']['main']['App']['LookupCarteraPorNIT'](arg1);
}

export function LookupMovimientosPorNIT(arg1) {
  return window['go']['main']['App']['LookupMovimientosPorNIT'](arg1);
}

export function LookupProducto(arg1) {
  return window['go']['main']['App']['LookupProducto'](arg1);
}

export function PauseSync() {
  return window['go']['main']['App']['PauseSync']();
}

export function RefreshCache(arg1) {
  return window['go']['main']['App']['RefreshCache'](arg1);
}

export function ResumeSync() {
  return window['go']['main']['App']['ResumeSync']();
}

export function RetryErrors(arg1) {
  return window['go']['main']['App']['RetryErrors'](arg1);
}

export function SaveConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchSyncHistory(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SearchSyncHistory'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}
