// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {parsers} from '../models';

export function ClearDatabase():Promise<string>;

export function ClearLogs():Promise<string>;

export function GetCartera(arg1:number,arg2:string):Promise<main.PaginatedISAM>;

export function GetClientes(arg1:number,arg2:string):Promise<main.PaginatedISAM>;

export function GetConfig():Promise<config.Config>;

export function GetExtfhStatus():Promise<Record<string, any>>;

export function GetISAMInfo():Promise<Array<main.ISAMPreview>>;

export function GetLogs(arg1:number):Promise<main.PaginatedLogs>;

export function GetMovimientos(arg1:number,arg2:string):Promise<main.PaginatedISAM>;

export function GetProductos(arg1:number,arg2:string):Promise<main.PaginatedISAM>;

export function GetStats():Promise<Record<string, any>>;

export function GetSyncHistory(arg1:string,arg2:number):Promise<main.PaginatedRecords>;

export function IsPaused():Promise<boolean>;

export function IsSyncing():Promise<boolean>;

export function LookupByNIT(arg1:string):Promise<parsers.Tercero>;

export function LookupCarteraPorNIT(arg1:string):Promise<Array<parsers.Cartera>>;

export function LookupMovimientosPorNIT(arg1:string):Promise<Array<parsers.Movimiento>>;

export function LookupProducto(arg1:string):Promise<parsers.Producto>;

export function PauseSync():Promise<string>;

export function RefreshCache(arg1:string):Promise<void>;

export function ResumeSync():Promise<string>;

export function RetryErrors(arg1:string):Promise<string>;

export function SaveConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function SearchSyncHistory(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<main.PaginatedRecords>;

export function SyncNow():Promise<string>;

export function TestConnection():Promise<string>;
