// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {storage} from '../models';

export function ClearDatabase():Promise<string>;

export function ClearLogs():Promise<string>;

export function GetClientes(arg1:number,arg2:string):Promise<main.PaginatedISAM>;

export function GetConfig():Promise<config.Config>;

export function GetISAMInfo():Promise<Array<main.ISAMPreview>>;

export function GetLogs(arg1:number):Promise<main.PaginatedLogs>;

export function GetMovimientos(arg1:number,arg2:string):Promise<main.PaginatedISAM>;

export function GetProductos(arg1:number,arg2:string):Promise<main.PaginatedISAM>;

export function GetRecordDetail(arg1:number):Promise<storage.SentRecord>;

export function GetSentRecords(arg1:string,arg2:number):Promise<main.PaginatedRecords>;

export function GetStats():Promise<Record<string, any>>;

export function IsPaused():Promise<boolean>;

export function IsSyncing():Promise<boolean>;

export function PauseSync():Promise<string>;

export function RefreshCache(arg1:string):Promise<void>;

export function ResendRecord(arg1:number):Promise<string>;

export function ResumeSync():Promise<string>;

export function SaveConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function SearchSentRecords(arg1:string,arg2:string,arg3:number):Promise<main.PaginatedRecords>;

export function SearchSentRecordsWithDates(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<main.PaginatedRecords>;

export function SyncNow():Promise<string>;

export function TestConnection():Promise<string>;
